server:
  port: 3001

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 150MB
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:mysql://localhost:3306/family_health
    username: root
    password: ${DB_PASSWORD:your_db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:your_mail_username}
    password: ${MAIL_PASSWORD:your_mail_password}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your_google_client_id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your_google_client_secret}
            redirect-uri: "${GOOGLE_REDIRECT_URI:http://localhost:3001/api/oauth2/google/callback}"
            scope: openid, profile, email

  kafka:
    bootstrap-servers: kafka:29092,localhost:9092
    consumer:
      group-id: email-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.value.default.type: com.hieuphinehehe.backend.dto.response.DataMailDTO
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

#JWT
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET:your_jwt_secret_key}
      expiration: 86400000 # 1 day in milliseconds
      refresh-token:
        expiration: 604800000 # 7 days in milliseconds

#SETUP spring openai
openai:
  api:
    key: ${OPENAI_API_KEY:your_openai_api_key}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash-latest:generateContent

#SETUP swagger
swagger:
  contact-name: Trinh Hieu Phi
  contact-mail: phitrinh367@gmail.com
  contact-url: https://www.facebook.com/hieuphihihihihi/
  app-name: Family Health
  app-description: "Family Health is built on Spring Boot + React"
  app-version: 3.3.1
  app-license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  app-license: Apache 2.0

#SETUP Cloudinary
cloudinary:
  cloud-name: dg0dwfewe
  api-key: ${CLOUDINARY_API_KEY:your_cloudinary_api_key}
  api-secret: ${CLOUDINARY_API_SECRET:your_cloudinary_api_secret}

stripe:
  api:
    key: ${STRIPE_API_KEY:your_stripe_api_key}
